version: "3.9"
services:
  app1:
    build: .
    container_name: app1
    networks: [webnet]
  app2:
    build: .
    container_name: app2
    networks: [webnet]

  haproxy:
    image: haproxy:2.9
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/certs:/certs:ro
    depends_on:
      - app1
      - app2
    networks: [webnet]

networks:
  webnet:
    driver: bridge
