version: "3.9"
services:
  app:
    image: ghcr.io/REEMPLAZA_OWNER/hello-java:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks: [webnet]

  haproxy:
    image: haproxy:2.9
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/certs:/certs:ro
    deploy:
      placement:
        constraints: [ "node.role == manager" ]
    networks: [webnet]

networks:
  webnet:
    driver: overlay
